# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nmX_qucYwpSaoEOxSKH1oqb-FuRCtZ_
"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import solve_ivp, cumulative_trapezoid


m = 1.0
I = 0.5
L_tether = 3.0
anchor = np.array([0.0, 0.0])

b_parallel = 0.01
b_perp = 50.0


r_f = np.array([0.5, -0.5])



def sleigh_physics(t, state):
  X, Y, theta, Vx, Vy, Omega = state

  c, s = np.cos(theta), np.sin(theta)
  R = np.array([[c, -s], [s, c]])

  e_para = np.array([c, s])
  e_perp = np.array([-s, c])

  r_com = np.array([X, Y])
  v_com = np.array([Vx, Vy])

  rf_global = R @ r_f
  v_f = v_com + Omega * np.array([-rf_global[1], rf_global[0]])

  F_f_para = -b_parallel * np.dot(v_f, e_para) * e_para
  F_f_perp = -b_perp * np.dot(v_f, e_perp) * e_perp
  F_friction = F_f_para + F_f_perp

  tau_friction = rf_global[0] * F_friction[1] - rf_global[1] * F_friction[0]


  r_vec = r_com - anchor
  r_dist = np.linalg.norm(r_vec)
  F_tension = np.array([0.0, 0.0])

  if r_dist > L_tether:
    k_spring = 200000.0
    c_damper = 500.0
    r_unit = r_vec / r_dist
    r_dot = np.dot(v_com, r_unit)
    magnitude = k_spring * (r_dist - L_tether) + c_damper * max(0, r_dot)
    F_tension = -magnitude * r_unit

  F_total = F_friction + F_tension
  ax = F_total[0] / m
  ay = F_total[1] / m
  alpha = tau_friction / I

  return [Vx, Vy, Omega, ax, ay, alpha]



state0 = [0.0, 2.5, 0.0, -3.0, 0.0, 1.0]
t_span = (0, 10)
t_eval = np.linspace(0, 10, 1000)

sol = solve_ivp(
    sleigh_physics, t_span, state0, t_eval=t_eval, method='Radau', rtol=1e-8
)


t = sol.t
X, Y, theta, Vx, Vy, Omega = sol.y


r = np.sqrt(X**2 + Y**2)
force_magnitude = np.zeros_like(r)


T_kinetic = 0.5 * m * (Vx**2 + Vy**2) + 0.5 * I * Omega**2
V_spring = np.zeros_like(r)
power_dissipation = np.zeros_like(r)

for i in range(len(t)):
  pos = np.array([X[i], Y[i]])
  vel = np.array([Vx[i], Vy[i]])
  om = Omega[i]
  th = theta[i]

  c, s = np.cos(th), np.sin(th)
  R = np.array([[c, -s], [s, c]])
  e_para = np.array([c, s])
  e_perp = np.array([-s, c])

  rf_global = R @ r_f
  v_f = vel + om * np.array([-rf_global[1], rf_global[0]])

  F_f_para = -b_parallel * np.dot(v_f, e_para) * e_para
  F_f_perp = -b_perp * np.dot(v_f, e_perp) * e_perp
  F_friction = F_f_para + F_f_perp
  tau_friction = rf_global[0] * F_friction[1] - rf_global[1] * F_friction[0]


  r_vec = pos - anchor
  r_dist = np.linalg.norm(r_vec)
  if r_dist > L_tether:
    k_spring = 200000.0
    c_damper = 500.0
    r_unit = r_vec / r_dist
    r_dot = np.dot(vel, r_unit)
    mag = k_spring * (r_dist - L_tether) + c_damper * max(0, r_dot)
    force_magnitude[i] = mag
    V_spring[i] = 0.5 * k_spring * (r_dist - L_tether)**2


  power_dissipation[i] = np.dot(F_friction, vel) + tau_friction * om


W_friction = cumulative_trapezoid(power_dissipation, t, initial=0)


E_total = T_kinetic + V_spring


fig, ax = plt.subplots(figsize=(6, 6))
ax.plot(X, Y, label='Sleigh Path', color='b')
ax.scatter([anchor[0]], [anchor[1]], color='r', s=100, label='Tether Anchor (0,0)')
ax.set_xlabel('X Position [m]')
ax.set_ylabel('Y Position [m]')
ax.grid(True)
ax.legend()
ax.set_aspect('equal')
plt.savefig('figure1_trajectory.pdf', format='pdf', bbox_inches='tight')
plt.show()


fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 5), sharex=True)
ax1.plot(t, r, color='b', lw=1.5, label='Radial Distance r(t)')
ax1.axhline(y=L_tether, color='r', linestyle='--', lw=1.2, label='Tether Limit L')
ax1.set_ylabel('Radius r [m]')
ax1.grid(True, linestyle=':', alpha=0.6)
ax1.legend(loc='upper right', frameon=True)

ax2.plot(t, force_magnitude, color='k', lw=1.0, label='Penalty Force Magnitude')
ax2.set_ylabel('Penalty Force [N]')
ax2.set_xlabel('Time t [s]')
ax2.grid(True, linestyle=':', alpha=0.6)
ax2.legend(loc='upper right', frameon=True)
plt.tight_layout()
plt.savefig('figure2_tethersnap.pdf', format='pdf', bbox_inches='tight')
plt.show()


fig, ax = plt.subplots(figsize=(6, 6))
ax.plot(Vx, Vy, color='purple', lw=1.2, label='Phase Trajectory')
ax.scatter([Vx[0]], [Vy[0]], color='green', s=50, zorder=5, label='Initial State')
ax.scatter([Vx[-1]], [Vy[-1]], color='red', s=50, zorder=5, label='Asymptotic Attractor')
ax.set_xlabel(r'Velocity Component $v_x$ [m/s]')
ax.set_ylabel(r'Velocity Component $v_y$ [m/s]')
ax.grid(True, linestyle=':', alpha=0.6)
ax.legend(loc='upper right', frameon=True)
plt.tight_layout()
plt.savefig('figure3_phasespace.pdf', format='pdf', bbox_inches='tight')
plt.show()


fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(6, 6), sharex=True)


ax1.plot(t, E_total, color='black', lw=1.5, label=r'$E_{\mathrm{total}}$')
ax1.plot(t, T_kinetic, color='blue', lw=1.2, linestyle='--', label=r'$T_{\mathrm{kinetic}}$')
ax1.plot(t, V_spring, color='red', lw=1.2, linestyle=':', label=r'$V_{\mathrm{spring}}$')
ax1.set_ylabel('Mechanical Energy [J]')
ax1.grid(True, linestyle=':', alpha=0.6)
ax1.legend(loc='upper right', frameon=True, fontsize=9.0)


ax2.plot(t, E_total, color='black', lw=1.5, label=r'$E_{\mathrm{total}}$')
ax2.plot(t, T_kinetic, color='blue', lw=1.2, linestyle='--', label=r'$T_{\mathrm{kinetic}}$')
ax2.plot(t, V_spring, color='red', lw=1.2, linestyle=':', label=r'$V_{\mathrm{spring}}$')
ax2.plot(t, W_friction, color='green', lw=1.2, linestyle='-.', label=r'$W_{\mathrm{friction}}$')
ax2.set_xlabel('Time t [s]')
ax2.set_ylabel('Energy / Work Ledger [J]')
ax2.grid(True, linestyle=':', alpha=0.6)
ax2.legend(loc='lower left', frameon=True, fontsize=9.0)

plt.tight_layout()
plt.savefig('figure4_energyledger.pdf', format='pdf', bbox_inches='tight')
plt.show()


r = np.sqrt(X**2 + Y**2)


max_penetration = np.max(r[r > L_tether] - L_tether)
print(f"Maximum radial penetration: {max_penetration:.6f} m")

force_magnitude = np.zeros_like(r)

from google.colab import files
import time

# Automatically download all four generated figures to your local computer
files.download('figure1_trajectory.pdf')
time.sleep(1)
files.download('figure2_tethersnap.pdf')
time.sleep(1)
files.download('figure3_phasespace.pdf')
time.sleep(1)
files.download('figure4_energyledger.pdf')

